version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --accesslog=true
      - --accesslog.format=json
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx:alpine
    container_name: nginx  # ¡IMPORTANTE!
    labels:
      - "traefik.enable=true"
      # Rate limiting estricto para pruebas
      - "traefik.http.middlewares.nginx-ratelimit.ratelimit.average=2"
      - "traefik.http.middlewares.nginx-ratelimit.ratelimit.burst=1"
      - "traefik.http.middlewares.nginx-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1"
      # Configuración del router
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.middlewares=nginx-ratelimit"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  api:
    image: containous/whoami
    container_name: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
